<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
      Schema::create('country', function (Blueprint $table) {
        $table->increments('id');
        $table->string('countryName')->nullable();
        $table->string('alpha2')->nullable();
        $table->string('currency')->nullable();
        $table->integer('status')->default(1)->comment('0 - Default, 1 - Active, 2 - Inactive, 3 - Deleted');
        $table->string('createdBy')->default(0);
        $table->timestamp('createdAt')->useCurrent();
        $table->string('updatedBy')->default(0);
        $table->timestamp('updatedAt')->default(DB::raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'));
      });

      DB::table('country')->insert([
        [ 'countryName' => "Afghanistan", 'alpha2' => 'AF', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Albania", 'alpha2' => 'AL', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Algeria", 'alpha2' => 'DZ', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Andorra", 'alpha2' => 'AD', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Angola", 'alpha2' => 'AO', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Argentina", 'alpha2' => 'AR', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Armenia", 'alpha2' => 'AM', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Austria", 'alpha2' => 'AT', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Australia", 'alpha2' => 'AU', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Azerbaijan", 'alpha2' => 'AZ', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Bahamas ", 'alpha2' => 'BS', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Bahrain", 'alpha2' => 'BH', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Bangladesh", 'alpha2' => 'BD', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Barbados", 'alpha2' => 'BB', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Belarus", 'alpha2' => 'BY', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Belgium", 'alpha2' => 'BE', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Belize", 'alpha2' => 'BZ', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Benin", 'alpha2' => 'BJ', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Bermuda", 'alpha2' => 'BM', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Bhutan", 'alpha2' => 'BT', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Bolivia", 'alpha2' => 'BO', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Bosnia and Herzegovina", 'alpha2' => 'BA', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Botswana", 'alpha2' => 'BW', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Brazil", 'alpha2' => 'BR', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Bulgaria", 'alpha2' => 'BG', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Burkina Faso", 'alpha2' => 'BF', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Burundi", 'alpha2' => 'BI', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Cabo Verde", 'alpha2' => 'CV', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Cameroon", 'alpha2' => 'CM', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Canada", 'alpha2' => 'CA', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Central African Republic", 'alpha2' => 'CF', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Chad", 'alpha2' => 'TD', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Chile", 'alpha2' => 'CL', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "China", 'alpha2' => 'CN', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Colombia", 'alpha2' => 'CO', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Congo (the Democratic Republic of the)", 'alpha2' => 'CD', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Congo", 'alpha2' => 'CG', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Costa Rica", 'alpha2' => 'CR', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Côte d'Ivoire ", 'alpha2' => 'CI', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Croatia", 'alpha2' => 'HR', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Cuba", 'alpha2' => 'CU', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Cyprus", 'alpha2' => 'CY', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Czech Republic", 'alpha2' => 'CZ', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Denmark", 'alpha2' => 'DK', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Djibouti", 'alpha2' => 'DJ', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Dominica", 'alpha2' => 'DM', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Dominican Republic", 'alpha2' => 'DO', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Ecuador", 'alpha2' => 'EC', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Egypt", 'alpha2' => 'EG', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Equatorial Guinea", 'alpha2' => 'GQ', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Eritrea", 'alpha2' => 'ER', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Estonia", 'alpha2' => 'EE', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Ethiopia", 'alpha2' => 'ET', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Falkland Islands", 'alpha2' => 'FK', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Faroe Islands", 'alpha2' => 'FO', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Fiji", 'alpha2' => 'FJ', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Finland", 'alpha2' => 'FI', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "France", 'alpha2' => 'FR', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "French Guiana", 'alpha2' => 'GF', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Gabon", 'alpha2' => 'GA', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Gambia", 'alpha2' => 'GM', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Georgia", 'alpha2' => 'GE', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Germany", 'alpha2' => 'DE', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Ghana", 'alpha2' => 'GH', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Gibraltar", 'alpha2' => 'GI', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Greece", 'alpha2' => 'GR', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Greenland", 'alpha2' => 'GL', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Grenada", 'alpha2' => 'GD', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Guam", 'alpha2' => 'GU', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Guatemala", 'alpha2' => 'GT', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Guinea", 'alpha2' => 'GN', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Guinea-Bissau", 'alpha2' => 'GW', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Guernsey", 'alpha2' => 'GG', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Guyana", 'alpha2' => 'GY', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Haiti", 'alpha2' => 'HT', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Honduras", 'alpha2' => 'HN', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Hong Kong", 'alpha2' => 'HK', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Hungary", 'alpha2' => 'HU', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "India", 'alpha2' => 'IN', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Indonesia", 'alpha2' => 'ID', 'status' => 1, 'currency' => 'Rp' ],
        [ 'countryName' => "Iran", 'alpha2' => 'IR', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Iraq", 'alpha2' => 'IQ', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Ireland", 'alpha2' => 'IE', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Isle of Man", 'alpha2' => 'IM', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Israel", 'alpha2' => 'IL', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Italy", 'alpha2' => 'IT', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Jamaica", 'alpha2' => 'JM', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Japan", 'alpha2' => 'JP', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Jersey", 'alpha2' => 'JE', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Jordan", 'alpha2' => 'JO', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Kazakhstan", 'alpha2' => 'KZ', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Kenya", 'alpha2' => 'KE', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Kiribati", 'alpha2' => 'KI', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Kuwait", 'alpha2' => 'KW', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Kyrgyzstan", 'alpha2' => 'KG', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Lao People's Democratic Republic", 'alpha2' => 'LA', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Latvia", 'alpha2' => 'LV', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Lebanon", 'alpha2' => 'LB', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Lesotho", 'alpha2' => 'LS', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Liberia", 'alpha2' => 'LR', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Libya", 'alpha2' => 'LY', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Liechtenstein", 'alpha2' => 'LI', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Lithuania", 'alpha2' => 'LT', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Luxembourg", 'alpha2' => 'LU', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Macao", 'alpha2' => 'MO', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Madagascar", 'alpha2' => 'MG', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Malawi", 'alpha2' => 'MW', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Malaysia", 'alpha2' => 'MY', 'status' => 1, 'currency' => 'RM' ],
        [ 'countryName' => "Maldives", 'alpha2' => 'MV', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Mali", 'alpha2' => 'ML', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Malta", 'alpha2' => 'MT', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Marshall Islands", 'alpha2' => 'MH', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Martinique", 'alpha2' => 'MQ', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Mauritania", 'alpha2' => 'MR', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Mauritius", 'alpha2' => 'MU', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Mexico", 'alpha2' => 'MX', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Micronesia", 'alpha2' => 'FM', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Moldova", 'alpha2' => 'MD', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Monaco", 'alpha2' => 'MC', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Mongolia", 'alpha2' => 'MN', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Montenegro", 'alpha2' => 'ME', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Montserrat", 'alpha2' => 'MS', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Morocco", 'alpha2' => 'MA', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Mozambique", 'alpha2' => 'MZ', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Myanmar ", 'alpha2' => 'MM', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Namibia", 'alpha2' => 'NA', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Nauru", 'alpha2' => 'NR', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Nepal", 'alpha2' => 'NP', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Netherlands", 'alpha2' => 'NL', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "New Caledonia", 'alpha2' => 'NC', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "New Zealand", 'alpha2' => 'NZ', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Nicaragua", 'alpha2' => 'NI', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Niger", 'alpha2' => 'NE', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Nigeria", 'alpha2' => 'NG', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Niue", 'alpha2' => 'NU', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Norfolk Island", 'alpha2' => 'NF', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "North Korea", 'alpha2' => 'KP', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "North Macedonia", 'alpha2' => 'MK', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Norway", 'alpha2' => 'NO', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Oman", 'alpha2' => 'OM', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Pakistan", 'alpha2' => 'PK', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Palau", 'alpha2' => 'PW', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Palestine", 'alpha2' => 'PS', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Panama", 'alpha2' => 'PA', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Papua New Guinea", 'alpha2' => 'PG', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Paraguay", 'alpha2' => 'PY', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Peru", 'alpha2' => 'PE', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Philippines ", 'alpha2' => 'PH', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Poland", 'alpha2' => 'PL', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Portugal", 'alpha2' => 'PT', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Puerto Rico", 'alpha2' => 'PR', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Qatar", 'alpha2' => 'QA', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Réunion", 'alpha2' => 'RE', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Romania", 'alpha2' => 'RO', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Russia", 'alpha2' => 'RU', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Rwanda", 'alpha2' => 'RW', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Samoa", 'alpha2' => 'WS', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "San Marino", 'alpha2' => 'SM', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Sao Tome and Principe", 'alpha2' => 'ST', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Saudi Arabia", 'alpha2' => 'SA', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Senegal", 'alpha2' => 'SN', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Serbia", 'alpha2' => 'RS', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Seychelles", 'alpha2' => 'SC', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Sierra Leone", 'alpha2' => 'SL', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Singapore", 'alpha2' => 'SG', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Slovakia", 'alpha2' => 'SX', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Slovenia", 'alpha2' => 'SI', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Solomon Islands", 'alpha2' => 'SB', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Somalia", 'alpha2' => 'SO', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "South Africa", 'alpha2' => 'ZA', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "South Korea", 'alpha2' => 'KR', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "South Sudan", 'alpha2' => 'SS', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Spain", 'alpha2' => 'ES', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Sri Lanka", 'alpha2' => 'LK', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Sudan", 'alpha2' => 'SD', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Suriname", 'alpha2' => 'SR', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Sweden", 'alpha2' => 'SE', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Switzerland", 'alpha2' => 'CH', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Syrian Arab Republic", 'alpha2' => 'SY', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Taiwan", 'alpha2' => 'TW', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Tajikistan", 'alpha2' => 'TJ', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Tanzania", 'alpha2' => 'TZ', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Thailand", 'alpha2' => 'TH', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Timor-Leste ", 'alpha2' => 'TL', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Togo", 'alpha2' => 'TG', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Tonga", 'alpha2' => 'TO', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Trinidad and Tobago", 'alpha2' => 'TT', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Tunisia", 'alpha2' => 'TN', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Turkey", 'alpha2' => 'TR', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Turkmenistan", 'alpha2' => 'TM', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Tuvalu", 'alpha2' => 'TV', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Uganda", 'alpha2' => 'UG', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Ukraine", 'alpha2' => 'UA', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "United Arab Emirates", 'alpha2' => 'AE', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "United Kingdom", 'alpha2' => 'GB', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "United States of America ", 'alpha2' => 'US', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Uruguay", 'alpha2' => 'UY', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Uzbekistan", 'alpha2' => 'UZ', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Vanuatu", 'alpha2' => 'VU', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Venezuela", 'alpha2' => 'VE', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Viet Nam", 'alpha2' => 'VN', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Virgin Islands (British) ", 'alpha2' => 'VG', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Virgin Islands (U.S.) ", 'alpha2' => 'VI', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Western Sahara", 'alpha2' => 'EH', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Yemen", 'alpha2' => 'YE', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Zambia", 'alpha2' => 'ZM', 'status' => 2, 'currency' => null ],
        [ 'countryName' => "Zimbabwe", 'alpha2' => 'ZW', 'status' => 2, 'currency' => null ],
      ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
      Schema::dropIfExists('country');
    }
};
